### ISSUE TITLE
access to your toolbox

### ISSUE THREAD

**Issue by Lancephil** [gpamic/toolbox_docs#1]
Good work. But how can I get access to your toolbox? pls.

**Comment by davidcoelho89** [comment]
Thank you for your interest in our toolbox, but we are still developing it (so, it is not public yet).
Also, we are using this repository for testing (and it should not be public - this was our mistake).
But are you interested in any particular algorithm?

**Comment by Lancephil** [comment]
Understood. I am interesting in lssvc, which is mentioned in your uploaded code, could you show me this part of the code?

**Comment by davidcoelho89** [comment]
Ok! This implementation is available at one of our contributors' github: 
https://github.com/RomuloDrumond/LSSVM
If you have any questions, you can ask him.
